### ISSUE TITLE
Sheet getting dismissed when state changes

### ISSUE THREAD

**Issue by ninoM** [silk-hq/community#51]
`@silk-hq/components@0.9.1`
[Minimal repro here](https://github.com/ninoM/silkhq-sheets-dismiss-issue)

https://github.com/user-attachments/assets/f77d0d5f-eedc-4ea9-8d54-eabb5ceb9736

# Steps
1. Create a separate component as the child of `Sheet.Content`. Let's call it `TestComponent` for this example.
2. Inside the `TestComponent` setup a boolean state. Then an boolean logic that switches between returning a `button` and a `button` inside any other html tag.

# Expected Outcome
The component will switch between two views without dismissing the Sheet.

# Actual Outcome
The Sheet dismisses when switching to the `button` inside another html tag.

**Comment by brunostasse** [comment]
Hi @ninoM, thank you for the detailed report and the reproduction!

I just published a fix. Please update to 0.9.2 and try again :)

**Comment by ukcw** [comment]
I'm still facing this issue @brunostasse, within the Sheet I am using the tabs component from shadcn
